---
jenkins_url: http://localhost:8080
jenkins_home: /var/lib/jenkins

# default admin
jenkins_admin_username: admin
jenkins_admin_password: admin

jenkins_plugins_list:
  - ant
  - antisamy-markup-formatter
  - build-timeout
  - cloudbees-folder
  - credentials-binding
  - email-ext
  - git
  - github-organization-folder 
  - gradle
  - ldap
  - mailer
  - matrix-auth
  - pam-auth
  - pipeline-stage-view
  - ssh-slaves
  - subversion
  - timestamper
  - workflow-aggregator
  - ws-cleanup