---
  - name: check grails is installed
    shell: bash -lc "sdk current grails"
    register: grails_installed_out
    become_user: jenkins

  - name: install grails 2.3 / 2.5
    shell: bash -lc "sdk install grails {{ item }}"
    when: not grails_installed_out.stdout | match("Using grails version {{ item }}")
    with_items:
      - "{{ grails_version_2_3 }}"
      - "{{ grails_version_2_5 }}"
    become_user: jenkins