---
java_home: /usr/lib/jvm/java-1.7.0-openjdk-i386

sdkman_dir: "{{ ansible_env.HOME}}/.sdkman"

gradle_home: "{{ sdkman_dir }}/candidates/gradle/current"

grails_home: "{{ sdkman_dir }}/candidates/grails/current"
