---
  - name: Add EPEL repository (CentOS-6)
    yum_repository:
      name: EPEL
      description: EPEL yum repo
      baseurl: http://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      gpgkey: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6
    when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"

  - name: Install EPEL (CentOS-7)
    yum:
      name: epel-release
    when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

  - name: Install pip (CentOS)
    yum:
      name: python-pip
      state: installed
      update_cache: yes
    when: ansible_distribution == 'CentOS'

  - name: Install pip (Ubuntu/Debian)
    apt:
      name: python-pip
      update_cache: yes
    when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
