---
- name: Create Jenkins job
  jenkins_job:
    config: "{{ lookup('template', 'templates/config.xml.j2') }}"
    name: ansible-lint
    user: "{{ jenkins_admin_user }}"
    password: "{{ jenkins_admin_pass }}"
    url: "{{ jenkins_url }}"
