---
- name: Install python-lxml via apt
  apt:
    name: python-lxml

- name: Install python-jenkins via pip
  pip:
    name: python-jenkins

- name: Create {{ docker_jenkins_home }} directory
  file:
    path: "{{ docker_jenkins_home }}"
    state: directory

- name: Copy files to server
  copy:
    src: files/plugins.txt
    dest: "{{ docker_jenkins_home }}"

- name: Copy templates to server
  template:
    src: "templates/{{ item }}.j2"
    dest: "{{ docker_jenkins_home }}/{{ item }}"
  with_items:
    - Dockerfile
    - security.groovy

- name: Build {{ docker_jenkins_image }} image
  docker_image:
    path: "{{ docker_jenkins_home }}"
    name: "{{ docker_jenkins_image }}"
    state: present

- name: Create {{ docker_jenkins_container }} container
  docker_container:
    name: "{{ docker_jenkins_container }}"
    image: "{{ docker_jenkins_image }}"
    published_ports:
      - "8080:8080"
      - "50000:50000"
