---
- name: Pull the Jenkins image
  docker_image:
    name: library/jenkins

- name: Create Jenkins container
  docker_container:
    name: jenkins
    image: jenkins
    published_ports:
      - "8080:8080"
      - "50000:50000"
