---
  - name: add jenkins key
    apt_key:
      url: http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key
      state: present

  - name: add jenkins repository
    apt_repository:
      repo: deb http://pkg.jenkins-ci.org/debian binary/
      state: present

  - name: install jenkins
    apt:
      name: jenkins
      update_cache: yes

  - name: create custom init scripts directory
    file:
      path: "{{ jenkins_home }}/init.groovy.d"
      state: directory
      owner: jenkins
      group: jenkins
      mode: 0775

  - name: create post-initialization script
    template:
      src: basic_security.groovy
      dest: "{{ jenkins_home }}/init.groovy.d/basic_security.groovy"
    notify: restart jenkins

  - name: install jenkins plugins
    jenkins_plugin:
      name: "{{ item }}"
    with_items: "{{ jenkins_plugins }}"
    notify: restart jenkins