---
  - name: Add Jenkins key
    apt_key:
      url: http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key
      state: present

  - name: Add Jenkins repository
    apt_repository:
      repo: deb http://pkg.jenkins-ci.org/debian binary/
      state: present

  - name: Install Jenkins
    apt:
      name: jenkins
      update_cache: yes

  - name: Disable Jenkins setup wizard
    copy:
      dest: /var/lib/jenkins/jenkins.install.InstallUtil.lastExecVersion
      content: 2.0
      owner: jenkins
      group: jenkins
      mode: 0755
    become: yes

  - name: Create post-initialization script
    template:
      src: init.groovy
      dest: "{{ jenkins_home }}/init.groovy"
      owner: jenkins
      group: jenkins
    notify: restart jenkins

  - name: Wait until Jenkins is available
    uri:
      url: "{{ jenkins_url }}/cli"
      status_code: 200
    register: result
    until: result.status == 200
    retries: 30
    delay: 1

  - name: Install Jenkins plugins
    include: plugins.yml