---
  - name: Disable Jenkins setup wizard
    copy:
      dest: /var/lib/jenkins/jenkins.install.InstallUtil.lastExecVersion
      content: 2.0
      owner: jenkins
      group: jenkins
      mode: 0755
    become: yes

  - name: Configure slave to master access control
    lineinfile:
      dest: "{{ jenkins_home }}/secrets/slave-to-master-security-kill-switch"
      line: false
      create: yes

  - name: Create post-initialization script
    template:
      src: init.groovy
      dest: "{{ jenkins_home }}/init.groovy"
      owner: jenkins
      group: jenkins
    notify: restart jenkins