---
  - name: Disable Jenkins setup wizard
    copy:
      dest: /var/lib/jenkins/jenkins.install.InstallUtil.lastExecVersion
      content: 2.0
      owner: jenkins
      group: jenkins
      mode: 0755

  - name: Create secrets directory
    file:
      path: "{{ jenkins_home }}/secrets/"
      state: directory
      mode: 0755

  - name: Configure slave to master access control
    template:
      src: slave-to-master-security-kill-switch
      dest: "{{ jenkins_home }}/secrets/slave-to-master-security-kill-switch"
      owner: jenkins
      group: jenkins
    notify: restart jenkins

  - name: Create post-initialization script
    template:
      src: init.groovy
      dest: "{{ jenkins_home }}/init.groovy"
      owner: jenkins
      group: jenkins
    notify: restart jenkins