---
- name: Install Python 2.7
  include_role:
    name: python-2.7
  when: ansible_python_version | version_compare('2.7.9', '<')

- name: Install packages to allow apt to use a repository over HTTPS
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add Docker’s official GPG key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"

- name: Set up the stable repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable

- name: Install Docker CE
  apt:
    name: docker-ce
    update_cache: yes
