---
  - name: install unzip
    apt: name=unzip

  - name: check sdk is installed
    shell: bash -lc "sdk version"
    register: sdk_installed_out
    failed_when: false
    become_user: jenkins

  - name: download sdkman installation script
    get_url: url=http://get.sdkman.io dest={{ jenkins_home }}/sdk_install.sh mode=0775 owner=jenkins group=jenkins
    when: not(sdk_installed_out.stdout | match("SDKMAN *"))

  - name: run sdkman script
    shell: "{{ jenkins_home }}/sdk_install.sh"
    when: not(sdk_installed_out.stdout | match("SDKMAN *"))
    become_user: jenkins

  - name: clean up sdkman installation script
    file: path={{ jenkins_home }}/sdk_install.sh state=absent
    when: not(sdk_installed_out.stdout | match("SDKMAN *"))
    become_user: jenkins

