---
  - name: install unzip
    apt: name=unzip

  - name: check sdk is installed
    shell: bash -lc "sdk version" executable=/bin/bash
    register: sdk_installed_out
    failed_when: false

  - name: download sdkman installation script
    get_url: url=http://get.sdkman.io dest=/home/{{ ansible_ssh_user }}/sdk_install.sh mode=0774
    when: not(sdk_installed_out.stdout | match("SDKMAN *"))

  - name: run sdkman script
    shell: /home/{{ ansible_ssh_user }}/sdk_install.sh
    when: not(sdk_installed_out.stdout | match("SDKMAN *"))

  - name: clean up sdkman installation script
    file: path=/home/{{ ansible_ssh_user }}/sdk_install.sh state=absent
    when: not(sdk_installed_out.stdout | match("SDKMAN *"))
