---
docker_jenkins_image: docker-jenkins
docker_jenkins_container: docker-jenkins
docker_jenkins_home: "{{ docker_home }}/docker-jenkins"

jenkins_url: http://localhost:8080

apt_packages:
  - python-pip

pip_packages:
  - ansible-lint
